services:
  user-management:
    image: user-management
    container_name: user-management
    build: .
    ports:
      - "5000:8080"
    environment:
      - FLUENTD_HOST=fluentd
      - FLUENTD_PORT=24224
    networks:
      - svc-network
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_LOG_STYLE=console
      - xpack.security.enabled=false
    volumes:
      - es-volume:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    expose:
      - "9200"
    networks:
      - elasticsearch
      - svc-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
      interval: 10s
      retries: 10
      start_period: 30s
  fluentd:
    image: fluentd
    container_name: fluentd
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - svc-network
      - elasticsearch
    depends_on:
      elasticsearch:
        condition: service_healthy
  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.3
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elasticsearch
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5601/api/status" ]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s
networks:
  svc-network:
    driver: bridge
  elasticsearch:
    driver: bridge
volumes:
  es-volume:
    driver: local
